In [1]:
!pip install vecstack

In [2]:
!pip install imblearn

In [3]:
from vecstack import stacking
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score #works
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
#from sklearn.ensemble import RandomForestClassifier
from imblearn.over_sampling import SMOTE 
from sklearn.svm import SVC
from collections import Counter #for Smote, 

import warnings
warnings.filterwarnings("ignore")

In [16]:
trainfile = r'C:\Users\dipti\Downloads\Cell Phone Churn - TRAIN-1.csv'
train_data = pd.read_csv(trainfile)

#train_data = pd.read_csv("C:\Users\dipti\Downloads\Cell Phone Churn - TRAIN-1.csv")


testfile = r'C:\Users\dipti\Downloads\Cell Phone Churn - TEST-1.csv'
test_data = pd.read_csv(testfile)

#test_data = pd.read_csv("C:\Users\dipti\Downloads\Cell Phone Churn - TEST-1.csv")


print(train_data.shape)
print(test_data.shape)
print(train_data.head())    
#pd = pd.replace(r'^\s*$', np.nan, regex=True)

(1695, 24)
(375, 24)
   MOUMO  MOUPMO  MOU3MO  MOUCH1M  MOUCH3M  CUM3MCH  CUSTMOS  LONGD  CALLW  \
0    105      15      99       90      -84        6       11      0      0   
1    999    1200    1145     -201       55     -146        3      1      1   
2      5       2       1        3        1        4       23      0      0   
3    600     456     398      144       58      202       13      0      1   
4      2       0       0        0        0        0        1      0      0   

   LINES  ...  INCOME  SPORTS NATURE ARTS  HRS_TV         TRAVEL        EDUC  \
0      2  ...   51000       B      1    N      10           None   Bachelors   
1      2  ...   80000       A      0    N      40       Domestic     Masters   
2      1  ...   80000       C      0    Y      50  International  HighSchool   
3      1  ...   88000       A      1    N       0  International     Masters   
4      1  ...   29000       B      0    N      75       Domestic  HighSchool   

  TOTMOU  TOTCHNG TARGET  
0 

In [17]:
X_train=train_data.iloc[:, :-1]
X_test=test_data.iloc[:, :-1]
y_train=train_data.iloc[:,-1]
y_test=test_data.iloc[:,-1]

print(y_train.shape)
print(y_test.shape)

(1695,)
(375,)


In [20]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1695 entries, 0 to 1694
Data columns (total 24 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   MOUMO    1695 non-null   int64 
 1   MOUPMO   1695 non-null   int64 
 2   MOU3MO   1695 non-null   int64 
 3   MOUCH1M  1695 non-null   int64 
 4   MOUCH3M  1695 non-null   int64 
 5   CUM3MCH  1695 non-null   int64 
 6   CUSTMOS  1695 non-null   int64 
 7   LONGD    1695 non-null   int64 
 8   CALLW    1695 non-null   int64 
 9   LINES    1695 non-null   int64 
 10  VOICEM   1695 non-null   int64 
 11  CELL     1695 non-null   int64 
 12  CONVB    1695 non-null   object
 13  SEX      1695 non-null   object
 14  INCOME   1695 non-null   int64 
 15  SPORTS   1695 non-null   object
 16  NATURE   1695 non-null   int64 
 17  ARTS     1695 non-null   object
 18  HRS_TV   1695 non-null   int64 
 19  TRAVEL   1695 non-null   object
 20  EDUC     1695 non-null   object
 21  TOTMOU   1695 non-null   int64 
 22  

In [21]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375 entries, 0 to 374
Data columns (total 24 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   MOUMO    375 non-null    int64 
 1   MOUPMO   375 non-null    int64 
 2   MOU3MO   375 non-null    int64 
 3   MOUCH1M  375 non-null    int64 
 4   MOUCH3M  375 non-null    int64 
 5   CUM3MCH  375 non-null    int64 
 6   CUSTMOS  375 non-null    int64 
 7   LONGD    375 non-null    int64 
 8   CALLW    375 non-null    int64 
 9   LINES    375 non-null    int64 
 10  VOICEM   375 non-null    int64 
 11  CELL     375 non-null    int64 
 12  CONVB    375 non-null    object
 13  SEX      375 non-null    object
 14  INCOME   375 non-null    int64 
 15  SPORTS   375 non-null    object
 16  NATURE   375 non-null    int64 
 17  ARTS     375 non-null    object
 18  HRS_TV   375 non-null    int64 
 19  TRAVEL   375 non-null    object
 20  EDUC     375 non-null    object
 21  TOTMOU   375 non-null    int64 
 22  TO

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size= 0.3, random_state=1)

In [25]:
#To get list of names of all Columns from a dataframe

TrainCols = list(train_data.columns.values)
TestCols = list(test_data.columns.values)
print(TrainCols)
print(TestCols)

['MOUMO', 'MOUPMO', 'MOU3MO', 'MOUCH1M', 'MOUCH3M', 'CUM3MCH', 'CUSTMOS', 'LONGD', 'CALLW', 'LINES', 'VOICEM', 'CELL', 'CONVB', 'SEX', 'INCOME', 'SPORTS', 'NATURE', 'ARTS', 'HRS_TV', 'TRAVEL', 'EDUC', 'TOTMOU', 'TOTCHNG', 'TARGET']
['MOUMO', 'MOUPMO', 'MOU3MO', 'MOUCH1M', 'MOUCH3M', 'CUM3MCH', 'CUSTMOS', 'LONGD', 'CALLW', 'LINES', 'VOICEM', 'CELL', 'CONVB', 'SEX', 'INCOME', 'SPORTS', 'NATURE', 'ARTS', 'HRS_TV', 'TRAVEL', 'EDUC', 'TOTMOU', 'TOTCHNG', 'TARGET']


In [26]:
# Seperate Target column from Train Data
X_train = train_data[TrainCols[0:len(TrainCols)-1]].copy()
y_train = train_data[['TARGET']].copy()
print("Train Set shape:")
print(X_train.shape)
print(y_train.shape)
X_test = test_data[TestCols[0:len(TestCols)-1]].copy()
y_test = test_data[['TARGET']].copy()
print("Test Set shape:")
print(X_test.shape)
print(y_test.shape)

Train Set shape:
(1695, 23)
(1695, 1)
Test Set shape:
(375, 23)
(375, 1)


In [27]:
#List of Categorical Features
categoricalFeatures = ['CONVB', 'SEX', 'SPORTS', 'NATURE', 'ARTS', 'TRAVEL', 'EDUC']

In [29]:
# OneHotEncoding on Train (fit & transform)
# OneHotEncoding is to be done on Categorical variables.
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(handle_unknown='ignore',sparse=False)
Xcat = pd.DataFrame(ohe.fit_transform(X_train[categoricalFeatures]),columns=ohe.get_feature_names(),index=X_train.index)
X_train = pd.concat([X_train,Xcat],axis=1)
X_train.drop(labels=categoricalFeatures,axis=1,inplace=True)
X_train.sample(5)

MOUMO  MOUPMO  MOU3MO  MOUCH1M  MOUCH3M  CUM3MCH  CUSTMOS  LONGD  CALLW  \
594     999    1200    1145     -201       55     -146        3      1      1   
1204     78      54      24       24       30       54        6      1      0   
737     555     444     678      111     -234     -123       27      1      1   
1378    100    9000      60    -8900     8940       40       10      1      0   
1594    333     277     144       56      133      189        9      0      1   

      LINES  ...  x5_Domestic  x5_InterGalactic  x5_International  x5_None  \
594       2  ...          1.0               0.0               0.0      0.0   
1204      1  ...          0.0               0.0               1.0      0.0   
737       2  ...          1.0               0.0               0.0      0.0   
1378      2  ...          1.0               0.0               0.0      0.0   
1594      1  ...          0.0               0.0               1.0      0.0   

      x6_Bachelors  x6_Elementary  x6_GED  x6_HighSchool  x6_Masters  x6_PhD  
594            0.0            0.0     0.0            0.0         0.0     1.0  
1204           1.0            0.0     0.0            0.0         0.0     0.0  
737            0.0            0.0     0.0            0.0         0.0     1.0  
1378           0.0            1.0     0.0            0.0         0.0     0.0  
1594           0.0            0.0     0.0            0.0         1.0     0.0  

[5 rows x 41 columns]

In [31]:
# OneHotEncoding on Test (only transform)
# OneHotEncoding is to be done on Categorical variables.
Xcat = pd.DataFrame(ohe.transform(X_test[categoricalFeatures]),columns=ohe.get_feature_names(),index=X_test.index)
X_test = pd.concat([X_test,Xcat],axis=1)
X_test.drop(labels=categoricalFeatures,axis=1,inplace=True)
X_test.sample(5)

MOUMO  MOUPMO  MOU3MO  MOUCH1M  MOUCH3M  CUM3MCH  CUSTMOS  LONGD  CALLW  \
312     97      56       5       41       51       92        8      0      0   
28     105      15      99       90      -84        6       11      0      0   
69       2       0       4        1       -3       -2        4      0      0   
128   1004     800     944      204     -144       60       26      1      1   
17    1004       4     944     1000     -940       60       26      1      1   

     LINES  ...  x5_Domestic  x5_InterGalactic  x5_International  x5_None  \
312      1  ...          1.0               0.0               0.0      0.0   
28       2  ...          0.0               0.0               0.0      1.0   
69       1  ...          0.0               0.0               0.0      1.0   
128      3  ...          0.0               0.0               0.0      1.0   
17       3  ...          0.0               0.0               0.0      1.0   

     x6_Bachelors  x6_Elementary  x6_GED  x6_HighSchool  x6_Masters  x6_PhD  
312           0.0            0.0     0.0            1.0         0.0     0.0  
28            1.0            0.0     0.0            0.0         0.0     0.0  
69            1.0            0.0     0.0            0.0         0.0     0.0  
128           0.0            0.0     0.0            0.0         0.0     1.0  
17            0.0            0.0     0.0            0.0         0.0     1.0  

[5 rows x 41 columns]

### Decision Tree

In [37]:
#CONSTRUCT DEFAULT DECISION TREE AND OBTAIN RESPECTIVE ACCURACY 
dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)
dt_predict=dt.predict(X_test)
print("accuracy Score (training) for Decision Tree:{0:6f}".format(dt.score(X_test,y_test)))
print("Confusion Matrix for Decision Tree")
print(confusion_matrix(y_test, dt_predict))

#get cross-validation report
dt_cv_score = cross_val_score(dt, X_train, y_train, cv=10, scoring="roc_auc")
print("=== All AUC Scores ===")
print(dt_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - Decision Tree: ",dt_cv_score.mean())

accuracy Score (training) for Decision Tree:0.994667
Confusion Matrix for Decision Tree
[[235   0]
 [  2 138]]
=== All AUC Scores ===
[0.99756781 0.99926297 1.         0.99978022 0.99838828 0.99047619
 0.99918155 1.         0.99910714 0.99888393]


=== Mean AUC Score ===
Mean AUC Score - Decision Tree:  0.9982648085994195


### MLP

In [38]:
#Construct MultiLayer Perceptron Model
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(max_iter=100)
mlp.fit(X_train, y_train)
mlp_predict=mlp.predict(X_test)
print("accuracy Score (training) for MultiLayer Perceptron:{0:6f}".format(mlp.score(X_test,y_test)))
print("Confusion Matrix for MultiLayer Perceptron:")
print(confusion_matrix(y_test,mlp_predict))

#get cross-validation report
mlp_cv_score = cross_val_score(mlp, X_train, y_train, cv=10, scoring="roc_auc")
print("=== All AUC Scores ===")
print(mlp_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - MultiLayer Perceptron: ",mlp_cv_score.mean())

accuracy Score (training) for MultiLayer Perceptron:0.808000
Confusion Matrix for MultiLayer Perceptron:
[[198  37]
 [ 35 105]]
=== All AUC Scores ===
[0.78456663 0.72626769 0.87736264 0.75479853 0.87516484 0.74196429
 0.74761905 0.86309524 0.696875   0.81011905]


=== Mean AUC Score ===
Mean AUC Score - MultiLayer Perceptron:  0.7877832942411362


### Linear SVC

In [34]:
#Construct Linear Support Vector Machine Model
from sklearn.svm import LinearSVC 
linsvm = LinearSVC(max_iter=300) 
linsvm.fit(X_train, y_train) 
linsvm_predict=linsvm.predict(X_test) 
print("accuracy Score (training) for Linear SVM Classifier:{0:6f}".format(linsvm.score(X_test,y_test))) 
print("Confusion Matrix for Linear SVM Classifier:") 
print(confusion_matrix(y_test,linsvm_predict))

accuracy Score (training) for Linear SVM Classifier:0.642667
Confusion Matrix for Linear SVM Classifier:
[[232   3]
 [131   9]]


### Random Forest

In [36]:
#Construct Random Forest Model

rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)
rfc_predict=rfc.predict(X_test)
print("accuracy Score (training) for RandomForest:{0:6f}".format(rfc.score(X_test,y_test)))
print("Confusion Matrix for Random Forest:")
print(confusion_matrix(y_test,rfc_predict))

#get cross-validation report
rfc_cv_score = cross_val_score(rfc, X_train, y_train, cv=10, scoring="roc_auc")
print("=== All AUC Scores ===")
print(rfc_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - Random Forest: ",rfc_cv_score.mean())

accuracy Score (training) for RandomForest:0.994667
Confusion Matrix for Random Forest:
[[235   0]
 [  2 138]]
=== All AUC Scores ===
[0.99756781 0.99926297 1.         0.99978022 0.99838828 0.99032738
 0.99918155 1.         0.99910714 0.99888393]


=== Mean AUC Score ===
Mean AUC Score - Random Forest:  0.9982499276470385


###  Hyperparameter Tuning for Random Forest

In [41]:
#Hyperparameter tuning for random forest classifier
parameters={'min_samples_split' : range(10,100,10),'max_depth': range(1,20,2)}
rfc_random = RandomizedSearchCV(rfc, parameters, n_iter=15)
rfc_random.fit(X_train, y_train)
grid_parm_rfc=rfc_random.best_params_
print(grid_parm_rfc)

#Construct Random Forest with best parameters
rfc= RandomForestClassifier(**grid_parm_rfc)
rfc.fit(X_train, y_train)
rfc_predict = rfc.predict(X_test)
print("accuracy Score (training) after hypertuning for Random Forest:{0:6f}".format(rfc.score(X_test, y_test)))
print("Confusion Matrix after hypertuning for Random Forest:")
print(confusion_matrix(y_test,rfc_predict))
print("=== Classification Report ===")
print(classification_report(y_test,rfc_predict))

#get cross-validation report
rfc_cv_score = cross_val_score(rfc, X_train, y_train, cv=10, scoring="roc_auc")
print("=== All AUC Scores ===")
print(rfc_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - Random Forest: ",rfc_cv_score.mean())


{'min_samples_split': 20, 'max_depth': 7}
accuracy Score (training) after hypertuning for Random Forest:0.994667
Confusion Matrix after hypertuning for Random Forest:
[[235   0]
 [  2 138]]
=== Classification Report ===
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       235
           1       1.00      0.99      0.99       140

    accuracy                           0.99       375
   macro avg       1.00      0.99      0.99       375
weighted avg       0.99      0.99      0.99       375

=== All AUC Scores ===
[0.99756781 0.99896816 1.         0.99978022 0.9985348  0.99397321
 0.99918155 1.         0.99895833 0.99888393]


=== Mean AUC Score ===
Mean AUC Score - Random Forest:  0.9985848009105676


In [42]:
#Hyperparameter tuning for random forest classifier
parameters={'min_samples_split' : range(15,100,20),'max_depth': range(1,20,2)}
rfc_random = RandomizedSearchCV(rfc, parameters, n_iter=15)
rfc_random.fit(X_train, y_train)
grid_parm_rfc=rfc_random.best_params_
print(grid_parm_rfc)

#Construct Random Forest with best parameters
rfc= RandomForestClassifier(**grid_parm_rfc)
rfc.fit(X_train, y_train)
rfc_predict = rfc.predict(X_test)
print("accuracy Score (training) after hypertuning for Random Forest:{0:6f}".format(rfc.score(X_test, y_test)))
print("Confusion Matrix after hypertuning for Random Forest:")
print(confusion_matrix(y_test,rfc_predict))
print("=== Classification Report ===")
print(classification_report(y_test,rfc_predict))

#get cross-validation report
rfc_cv_score = cross_val_score(rfc, X_train, y_train, cv=10, scoring="roc_auc")
print("=== All AUC Scores ===")
print(rfc_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - Random Forest: ",rfc_cv_score.mean())

{'min_samples_split': 15, 'max_depth': 7}
accuracy Score (training) after hypertuning for Random Forest:0.994667
Confusion Matrix after hypertuning for Random Forest:
[[235   0]
 [  2 138]]
=== Classification Report ===
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       235
           1       1.00      0.99      0.99       140

    accuracy                           0.99       375
   macro avg       1.00      0.99      0.99       375
weighted avg       0.99      0.99      0.99       375

=== All AUC Scores ===
[0.99815743 0.99926297 1.         0.99978022 0.99838828 0.98474702
 0.99918155 1.         0.99910714 0.99888393]


=== Mean AUC Score ===
Mean AUC Score - Random Forest:  0.9977508541969037


In [43]:
#Hyperparameter tuning for random forest classifier
parameters={'min_samples_split' : range(10,100,20),'max_depth': range(1,20,5)}
rfc_random = RandomizedSearchCV(rfc, parameters, n_iter=15)
rfc_random.fit(X_train, y_train)
grid_parm_rfc=rfc_random.best_params_
print(grid_parm_rfc)

#Construct Random Forest with best parameters
rfc= RandomForestClassifier(**grid_parm_rfc)
rfc.fit(X_train, y_train)
rfc_predict = rfc.predict(X_test)
print("accuracy Score (training) after hypertuning for Random Forest:{0:6f}".format(rfc.score(X_test, y_test)))
print("Confusion Matrix after hypertuning for Random Forest:")
print(confusion_matrix(y_test,rfc_predict))
print("=== Classification Report ===")
print(classification_report(y_test,rfc_predict))

#get cross-validation report
rfc_cv_score = cross_val_score(rfc, X_train, y_train, cv=10, scoring="roc_auc")
print("=== All AUC Scores ===")
print(rfc_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - Random Forest: ",rfc_cv_score.mean())



{'min_samples_split': 50, 'max_depth': 6}
accuracy Score (training) after hypertuning for Random Forest:0.994667
Confusion Matrix after hypertuning for Random Forest:
[[235   0]
 [  2 138]]
=== Classification Report ===
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       235
           1       1.00      0.99      0.99       140

    accuracy                           0.99       375
   macro avg       1.00      0.99      0.99       375
weighted avg       0.99      0.99      0.99       375

=== All AUC Scores ===
[0.99653597 0.99823113 1.         0.9989011  0.9978022  0.98854167
 0.99799107 1.         0.99791667 0.99799107]


=== Mean AUC Score ===
Mean AUC Score - Random Forest:  0.9973910871950377


In [44]:
from sklearn.feature_selection import SelectFromModel
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2, f_classif

In [49]:
#K-BEST FEATURE Selection =================================================================================
#====================================================================================================
#Feature Selection
fs = SelectKBest(f_classif, k=5)

fs.fit(X_train, y_train)
feature_index = fs.get_support(True)
print ("feature index =", feature_index)

#f_value, p_value = f_classif(X_train, y_train)
#print (feature_index.tolist(), f_value, p_value) 

feature index = [16 17 20 32 33]


In [50]:
#Feature selection-Continued
fs = SelectKBest(f_classif, k=10)
new_X_train = fs.fit_transform(X_train,y_train)
print(new_X_train.shape)

new_X_train_SelectedFeatures= pd.DataFrame(new_X_train)
print(new_X_train_SelectedFeatures)

export_csv= new_X_train_SelectedFeatures.to_csv(r'C:\Users\dipti\Downloads\new_X_train_Selected-Features-Selected Features.csv')


(1695, 10)
        0    1    2    3    4    5    6    7    8    9
0     0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
1     1.0  1.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0
2     0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0
3     1.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0
4     0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
1690  1.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0
1691  1.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0
1692  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
1693  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
1694  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0

[1695 rows x 10 columns]


In [51]:
#Apply feature selection to test data also

new_X_test = fs.transform(X_test)
print(new_X_test.shape)


new_X_test_SelectedFeatures= pd.DataFrame(new_X_test)
print(new_X_test_SelectedFeatures)

export_csv= new_X_test_SelectedFeatures.to_csv(r'C:\Users\dipti\Downloads\new_X_test_Selected-Features-Selected Features.csv')


(375, 10)
       0    1    2    3    4    5    6    7    8    9
0    1.0  1.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0
1    1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
2    0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0
3    1.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0
4    1.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
370  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
371  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
372  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0
373  0.0  0.0  1.0  0.0  1.0  1.0  0.0  0.0  1.0  0.0
374  1.0  1.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0

[375 rows x 10 columns]


In [54]:
print("___________________________________________________________________________________________\nEnsemble Methods Predictions using GradientBoosting, RandomForest and Decision Tree Classifier\n")

models = [ MLPClassifier(), LinearSVC(), RandomForestClassifier(), DecisionTreeClassifier() ]
      
S_Train, S_Test = stacking(models,                   
                           X_train, y_train, X_test,   
                           regression=False, 
     
                           mode='oof_pred_bag', 
       
                           needs_proba=False,
         
                           save_dir=None, 
            
                           metric=accuracy_score, 
    
                           n_folds=4, 
                 
                           stratified=True,
            
                           shuffle=True,  
            
                           random_state=0,    
         
                           verbose=2)


___________________________________________________________________________________________
Ensemble Methods Predictions using GradientBoosting, RandomForest and Decision Tree Classifier

task:         [classification]
n_classes:    [2]
metric:       [accuracy_score]
mode:         [oof_pred_bag]
n_models:     [4]

model  0:     [MLPClassifier]
    fold  0:  [0.72877358]
    fold  1:  [0.69103774]
    fold  2:  [0.72877358]
    fold  3:  [0.45626478]
    ----
    MEAN:     [0.65121242] + [0.11360250]
    FULL:     [0.65132743]

model  1:     [LinearSVC]
    fold  0:  [0.64150943]
    fold  1:  [0.63915094]
    fold  2:  [0.62971698]
    fold  3:  [0.41607565]
    ----
    MEAN:     [0.58161325] + [0.09567498]
    FULL:     [0.58171091]

model  2:     [RandomForestClassifier]
    fold  0:  [0.98113208]
    fold  1:  [0.98820755]
    fold  2:  [0.98820755]
    fold  3:  [0.99290780]
    ----
    MEAN:     [0.98761374] + [0.00420548]
    FULL:     [0.98761062]

model  3:     [DecisionTreeC

In [56]:
model = MLPClassifier()
    
model = model.fit(S_Train, y_train)
y_pred = model.predict(S_Test)
print('Final prediction score for ensemble methods: [%.8f]' % accuracy_score(y_test, y_pred))

Final prediction score for ensemble methods: [0.99466667]
